- doc_source/build-spec-ref.md
Changed "buildpec"to "build spec".
Apologies for the non-change on line 394; I guess the GitHub web editor has added/removed something from the end of the document.
> Fix "buildpec" typo

- doc_source/sample-multi-in-out.md
Tabs are not valid in the buildspec YAML
[Container] 2019/04/14 02:10:17 Phase context status code: YAML_FILE_ERROR Message: found character that cannot start any token at line 3 
Change documentation to use 2 spaces instead of \t
> Fix invalid YAML tabs in inline buildspec

- doc_source/build-spec-ref.md
This removes an extra "name" key in the example buildspec for producing multiple secondary artifacts.
> Remove extraneous name key in example buildspec

- doc_source/troubleshooting.md
*Issue:*
When Codebuild attempts to use a build image from ECR in a different region the following error occurs: 'BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image.'
I have added the cause and resolution into the documentation.
> Added: resolution for Codebuild using different ECR region

- doc_source/sample-docker.md
This is just to add the missing `"privilegedMode": true` to the JSON\-formatted input to the `create-project` command, as using CodeBuild to build Docker requires privilegedMode = true.
> Docker build with CodeBuild requires privilegedMode

- doc_source/sample-github-enterprise.md
- doc_source/sample-github-pull-request.md
*Issue #, if available:* 
Current webhook sample states that it can be created for private repositories. This is not accurate since we can configure webhooks on public repositories too.
Updated the descriptions in the sample, and callout that you can use filter groups to avoid unnecessary builds triggered by changes in public repositories.
> Update GitHub and GHE webhook sample

- doc_source/sample-access-tokens.md
Name of one of the links looks to be copy pasted too fast
Changed "Use a Proxy ServerCommand Line Reference." to be just "Command Line Reference." which is the name of the page the link leads to.
> Fix name of CLI Reference link

- doc_source/build-spec-ref.md
changed 'arifact' to 'artifact'
> Fix typo in word 'artifact'

- doc_source/build-spec-ref.md
> Typo in java runtime name

- doc_source/notification-rule-create.md
When calling `aws codestarnotifications` cli returns:
Invalid choice: 'codestarnotifications', maybe you meant:
* codestar-notifications
Based on that updated command names.
> Fix CLI command name

- doc_source/build-env-ref-available.md
There is no php7.4 in CodeBuild Linux environment
> Removed 7.4

- doc_source/use-codebuild-agent.md
Updated the SHA256 signature of the amazon/aws-codebuild-local docker image to reflect the current version.
> Update amazon/aws-codebuild-local signature

- doc_source/sample-runtime-versions.md
nothing
I found mismatched Go version on sample-runtime-versions.md.
updated to 1.13 in [this commit](https://github.com/awsdocs/aws-codebuild-user-guide/commit/9375175ac5d3bbf7ec8d138f1f6d8fa504e9a08e) however 1.12 remains.
> Fix Go versions on sample-runtime-versions.md

- doc_source/sample-ecr.md
The sample policy shows only one case, the cross-account CodeBuildAccess.
I've included the sample code for a policy with the most common use-case of the CodeBuild principal and as the second case the cross-account CodeBuildAccess.
> Sample policy for CodeBuildAccess, with both cases

- doc_source/sample-buildspec-artifact-naming.md
*Issue #, if available:* Spelling typo for "multiple"
*Description of changes:* Changed "mulitple" to "multiple"
> Fix spelling mistake "mulitple" to "multiple"

- doc_source/build-spec-ref.md
Fix wrong name for parameter git-credential-helper.
> Fix wrong name for parameter git-credential-helper

- doc_source/auth-and-access-control-permissions-reference.md
No open issue.
Until recently, "stop" and "start" IAM actions alone, allowed us to retry execution of a codebuild project (using the Retry button).
As of recent, out of (What felt to me at least) no where, we can no longer retry execution of builds while having just "stop" and "start" actions in the IAM policy. getting unauthorized.
After looking at the IAM policy visualizer now (us-east-1), I see there's a "RetryBuild" action, which is required.
I couldn't find the RetryBuild action in the docs, so adding it via this PR. 
Thanks.
> add missing RetryBuild action

- doc_source/sample-pipeline-multi-input-output.md
The example as written does not work.  The [AWS CodeBuild specification](https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html) provides a better example and this is a partial copy of that.
I only added the `files` section to the `artifacts` element.  I don't know why the `After you create the JSON file...` line keeps getting stuck in there but I'm leaving it alone.  
> fix artifacts example

- CONTRIBUTING.md
- doc_source/build-spec-ref.md
N/A
I found a few indentation errors in the example buildspec syntax as well as some lingering refs to master branch
> Fixed a few indentation errors and master->main occurrences

- doc_source/use-codebuild-agent.md
N/A
Standard 5.0 image was released on 2021/01/08
https://github.com/aws/aws-codebuild-docker-images/releases/tag/21.01.08
> Use standard:5.0 in local codebuild guide

- doc_source/use-codebuild-agent.md
*Issue #, if available:* N/A
The "Set up the build image" steps instruct the user how to install version 5 of the image however the run steps still say to run version 4. 
> Fix agent version in Run the CodeBuild agent steps

- doc_source/github-webhook.md
... because it belongs to the type filtergroup item above and is not a new item in the list.
> fix: remove dash from COMMIT_MESSAGE pattern item

- doc_source/how-to-create-pipeline.md
BitBucket is now a supported source provider in CodePipeline (https://aws.amazon.com/about-aws/whats-new/2019/12/aws-codepipeline-now-supports-atlassian-bitbucket-cloud/).
Removed reference saying Bitbucket is unsupported. Added Bitbucket as a supported source code repository.
> Bitbucket is now a supported source provider in CodePipeline
